name: checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  clippy:
    runs-on: ubuntu-latest
    name: "Check & Clippy"

    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.73.0" # MSRV
          override: true
          components: clippy

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: check

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --no-deps -- -D warnings
          name: "Clippy Results"

  rustdoc:
    runs-on: ubuntu-latest
    name: "Rustdoc"

    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          minimal: true

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: rustdoc
          args: -p taskchampion --all-features -- -Z unstable-options  --check -Dwarnings

  mdbook:
    runs-on: ubuntu-latest
    name: "mdBook Documentation"

    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          # if this changes, change it in .github/workflows/publish-docs.yml as well
          mdbook-version: '0.4.10'

      - run: mdbook test docs
      - run: mdbook build docs

  fmt:
    runs-on: ubuntu-latest
    name: "Formatting"
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --all -- --check

